name: Deploy to WeChat CloudBase

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install WxCloud CLI
        run: npm install -g @wxcloud/cli

      - name: Login to WxCloud
        run: |
          wxcloud login --appid ${{ secrets.WXAPPID }} --key ${{ secrets.WXAPP_KEY }}

      - name: Deploy to WxCloud
        run: |
          wxcloud deploy --mode prod --env ${{ secrets.ENV_ID }}
